version: '3.1'
services:
  postgresSQL:
    image: "postgres:latest"
    container_name: haccp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    networks:
      - haccpnet


  keycloak:
    image: "quay.io/keycloak/keycloak:21.1.1"
    container_name: keycloakHaccp
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      KEYCLOAK_ADMIN : "admin"
      KEYCLOAK_ADMIN_PASSWORD : "admin"
    volumes:
      - ./SpringBootKeycloak-realm.json:/opt/keycloak/data/import/SpringBootKeycloak-realm.json
    command:
      - start-dev
      - --import-realm
    networks:
      - haccpnet

networks:
  haccpnet: